import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreWrapper } from "./StoreContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <StoreWrapper>{children}</StoreWrapper>;
}
